# Use official Node image
FROM node:18

# Create app directory inside container
WORKDIR /app

# Copy only package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the code
COPY . .

# Expose backend port
EXPOSE 3000

# Start server
CMD ["node", "src/server.js"]